<?xml version="1.0" encoding="utf-8"?><Database Name="DOANWEB" Class="DBAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-15VCGIA\SQLEXPRESS;Initial Catalog=DOANWEB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DOANWEBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MASP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUC" Member="DANHMUCs">
    <Type Name="DANHMUC">
      <Column Name="MADM" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="DANHMUC_SANPHAM" Member="SANPHAMs" ThisKey="MADM" OtherKey="MADM" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNGUOINHAN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(12)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PTTT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MAND" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHOADON" />
      <Association Name="NGUOIDUNG_HOADON" Member="NGUOIDUNG" ThisKey="MAND" OtherKey="MAND" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="MAND" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENND" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(12)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="[LEVEL]" Member="LEVEL" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="NGUOIDUNG_HOADON" Member="HOADONs" ThisKey="MAND" OtherKey="MAND" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MADM" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BAOHANH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="KHUYENMAI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NOIBAT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETHOADON" />
      <Association Name="DANHMUC_SANPHAM" Member="DANHMUC" ThisKey="MADM" OtherKey="MADM" Type="DANHMUC" IsForeignKey="true" />
    </Type>
  </Table>
</Database>